apiVersion: v1
kind: Pod
metadata:
  name: log-generator
spec:
  containers:
  - name: log-generator
    image: busybox
    command: ['sh', '-c', 'i=0; while true; do echo "$i: Log message"; i=$((i+1)); sleep 1; done']
