name: "> Build"

concurrency: no-concurrency # no concurrency

env:
  GAR_LOCATION: us-central1
  REPOSITORY: my-repo
  IMAGE: sample

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "source/*.js"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Authenticate to Google Cloud
        id: gcloud-auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SAC_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1.1.0

      - name: Docker configuration
        run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev --quiet

      # Build the Docker image
      - name: Build
        # env:
        #   PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |-
          cd source
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$GCP_PROJECT/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      # Push the Docker image to Google Artifact Registry
      - name: Publish
        # env:
        #   PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |-
          cd source
          docker push "$GAR_LOCATION-docker.pkg.dev/$GCP_PROJECT/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)

      - name: Deploy to Cluster
        run: |
          cd source
          cat sample.yaml
          sed -i'' -e 's/PROJECT_LABEL/${{ env.GCP_PROJECT }}/g' sample.yaml
          sed -i'' -e 's/IMAGE_LABEL/${{ github.sha }}/g' sample.yaml
          cat sample.yaml
          kubectl apply -f sample.yaml

      # - name: kubectl apply
      #   run: |-
      #     kubectl set image deployment/sample sample=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
      #     kubectl create deployment tmp --image=us-central1-docker.pkg.dev/newops14/my-repo/sample@sha256:2e4fcf2fd657ea59ec133034ddacad784c34abe450b2b0a4e709589406524dd3 --port=8090

      # - name: Clone repo
      #   uses: actions/checkout@main
      #   with:
      #     repository: cloud-native-engineering/new-cloud-provisioning
      #     ref: main

      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: ${{ env.TF_VERSION }}
      #     terraform_wrapper: false

      # - name: Install Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "16"

      # - name: Generate Terraform Project Code
      #   id: generate_project
      #   uses: ./.github/actions/generate_project
      #   with:
      #     environment: ${{ secrets.ENVIRONMENT }}
      #     project_name: ${{ secrets.PROJECT_NAME }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     folder: projects

      # # TODO: not the best approach
      # - name: clean-netrc
      #   run: |
      #     rm -f $HOME/.netrc || true

      # # TODO: not the best approach
      # - name: Git Credentials for Terraform
      #   uses: little-core-labs/netrc-creds@master
      #   with:
      #     machine: git.epo.org
      #     login: oauth2
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Authenticate to Google Cloud
      #   id: gcloud-auth
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.SAC_KEY }}

      # - name: Setup gcloud
      #   uses: google-github-actions/setup-gcloud@v1.1.0

      # - name: Terraform Plan
      #   env:
      #     VAULT_ROLE_ID: ${{ secrets.VAULT_APPROLE_ID }}
      #     VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      #     VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      #   run: |
      #     set -e
      #     set -o pipefail
      #     terraform -chdir="./projects/${{ secrets.ENVIRONMENT }}/${{ secrets.PROJECT_NAME }}/generated" fmt -no-color -check
      #     terraform -chdir="./projects/${{ secrets.ENVIRONMENT }}/${{ secrets.PROJECT_NAME }}/generated" init -no-color -input=false
      #     terraform -chdir="./projects/${{ secrets.ENVIRONMENT }}/${{ secrets.PROJECT_NAME }}/generated" validate -no-color
      #     terraform -chdir="./projects/${{ secrets.ENVIRONMENT }}/${{ secrets.PROJECT_NAME }}/generated" plan -refresh=true -input=false -no-color -out=$GITHUB_WORKSPACE/$PLAN_CACHE
      #     if [ -f "$GITHUB_WORKSPACE/$PLAN_CACHE" ]; then
      #       terraform -chdir="./projects/${{ secrets.ENVIRONMENT }}/${{ secrets.PROJECT_NAME }}/generated" show --json $GITHUB_WORKSPACE/$PLAN_CACHE > $GITHUB_WORKSPACE/$PLAN_FILE
      #     fi

      # - name: Validate Terraform Plan
      #   id: validate_plan
      #   uses: ./.github/actions/validate_tf_plan
      #   with:
      #     file: ${{ github.workspace }}/${{ env.PLAN_FILE }}

      # - name: Terraform Apply
      #   env:
      #     VAULT_ROLE_ID: ${{ secrets.VAULT_APPROLE_ID }}
      #     VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      #     VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      #   run: |
      #     set -e
      #     set -o pipefail
      #     if [ -f "$GITHUB_WORKSPACE/$PLAN_CACHE" ]; then
      #       terraform -chdir="./projects/${{ secrets.ENVIRONMENT }}/${{ secrets.PROJECT_NAME }}/generated" apply -auto-approve -no-color $GITHUB_WORKSPACE/$PLAN_CACHE
      #     fi

      # - name: Deploy Services
      #   id: deploy_services
      #   uses: ./.github/actions/deploy_services
      #   with:
      #     file: ./projects/${{ secrets.ENVIRONMENT }}/${{ secrets.PROJECT_NAME }}/generated/crs
      #     projectRegion: ${{ secrets.PROJECT_REGION }}
      #     projectId: ${{ secrets.PROJECT_ID }}
      #     projectName: ${{ secrets.PROJECT_NAME }}
      #     environment: ${{ secrets.ENVIRONMENT }}
      #     dryRun: false
      #     deleted: ${{ steps.validate_plan.outputs.deleted }}
